BEVCamera: true
large_vehicles: false
invisible_ego: false
invisible_all: false
3Dboundingbox: true
sort_spawnpoints: true
other_vehicles_have_sensors: true
carla:
  fixed_delta_seconds: 0.1
  host: localhost
  port: 2000
  synchronous_mode: true
  timeout: 40.0
data_dir: data
dataset:
  nuscenes_lidar:
    attached_to_vehicle: true
    sensor_info:
      channels: 32
      points_per_second: 90000
      rotation_frequency: 40
      range: 20
      type:
      - sensor.lidar.ray_cast
    transform_file_lidar: /seed4d/config/lidar/nuscenes/nuscenes_adjusted.json
  nuscenes:
    attached_to_vehicle: true
    sensor_info:
      fov: 90
      height: 128
      width: 256
      type:
      - sensor.camera.rgb
      - sensor.camera.semantic_segmentation
      - sensor.camera.instance_segmentation
      - sensor.camera.depth
      - sensor.camera.optical_flow
    transform_file_cams: /seed4d/config/camera/nuscenes/nuscenes_adjusted.json
  sphere:
    attached_to_vehicle: true
    sensor_info:
      fov: 90
      height: 96
      width: 128
      type:
      - sensor.camera.rgb
      - sensor.camera.semantic_segmentation
      - sensor.camera.instance_segmentation
      - sensor.camera.depth
      - sensor.camera.optical_flow
    transform_file_cams: /seed4d/config/camera/sphere/sphere-10.json
map: Town01
min_distance: 0.0
number_of_vehicles: 20
number_of_walkers: 20
spawn_point:
- 1
steps: 100
vehicle: vehicle.mini.cooper_s
weather: ClearNoon